bug(coverage): fix issues from Code Climate bot
Error: The test coverage on the diff in this pull request is 0.0% (50% is the threshold).

We introduced a `welcome.js` file that didn't have test coverage. We need to ignore this file from Jest coverage tool, Instanbul.

- https://codewithhugo.com/jest-exclude-coverage/